set nocompatible              " be iMproved, required

" Rebinds k and j to count wrapped lines as new lines but still work with a motion in front
nnoremap <expr> k (v:count == 0 ? 'gk' : 'k')
nnoremap <expr> j (v:count == 0 ? 'gj' : 'j')
nmap <Up> k
nmap <Down> j

" Remaps split navigation keys
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-h> <C-w>h

" Tab specific option
set tabstop=4                  "A tab is 8 spaces
"set expandtab                   "Always uses spaces instead of tabs
set softtabstop=4               "Insert 4 spaces when tab is pressed
set shiftwidth=4                "An indent is 4 spaces
set shiftround                  "Round indent to nearest shiftwidth multiple

let mapleader = ","
nnoremap <Leader>s :%s/\<<C-r><C-w>\>/

set pastetoggle=<F2>

set incsearch		" find the next match as we type the search
set ignorecase		" set search to be case insensitive 
set smartcase		" unless you typed uppercase letters in your query"
set autoindent		" For autoindenting after a newline
set showcmd			" Shows what you are typing as a command
set mouse=a			" Enable mouse in terminal
set number			" Numbered lines
set scrolloff=5		" No longer need to place cursor att bottom to scroll

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

" Vim-airline statusbar
set laststatus=2
set noshowmode
set timeoutlen=100
let g:airline_powerline_fonts = 1
